name: generate_pdf_report
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas=1.3.5
  - reportlab=4.4.1
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - pillow=11.2.1
